### ISSUE TITLE
Cannot specify no default with an init for an option

### ISSUE THREAD

**Issue by jamesarosen** [leo/args#101]
Given
```js
args
  .option('foo', 'Foo', null, function(value) {
    return value || process.env.FOO || 'null'
  })
const flags = args.parse(process.argv)
console.log(flags.foo)
```
I expect
```bash
$ my-command
null
$ FOO=bar my-command
bar
$ my-command --foo=baz
baz
```

But in fact, the `init` callback is never called.

**Comment by ntwcklng** [comment]
Hey jamesarosen,

its because the `defaultValue` is `null`. Try to set your `defaultValue` to an empty string.

**Comment by jamesarosen** [comment]
> Try to set your `defaultValue` to an empty string

That's probably fine for my case, but it's not the same as not passing a value for that argument:

```js
args.option('foo', 'Foo')
args.parse() // {}

args.option('foo', 'Foo', '')
args.parse() // { f: '', foo: '' }
```

**Comment by ntwcklng** [comment]
i think thats the right way. We won't guess the type of `foo` when its not specified. You should always add a defaultValue, so `args` knows what type to expect. 

Maybe we should make it a required argument? cc @leo
