### ISSUE TITLE
subcommands can't have a --version option

### ISSUE THREAD

**Issue by jamesarosen** [leo/args#103]
A primary command can take a `--version` option with the following code:
```js
args.option('version', 'The version of the thing');

const flags = args.parse(process.argv, {
  version: false,
});
```

When I run `my-command my-subcommand --help`, I see

```
 -v, --version        The version of the thing
```

But when I run `my-command my-subcommand --version=foo`, `flags.version` is unpopulated.

**Comment by jamesarosen** [comment]
Whoops. I think I may have been running the wrong version of my script. I can't reproduce this now.

**Comment by jamesarosen** [comment]
The `--version` does work if I specify `version: false` in both the super-command _and_ the sub-command.

**Comment by ntwcklng** [comment]
This example works for me:
`foo.js`
```js
#!/usr/bin/env node

const args = require('args')

args
  .option('version', 'version opt main')
  .command('bar', 'subcmd')

const flags = args.parse(process.argv, {version: false})
```

`foo-bar.js`
```js
#!/usr/bin/env node

const args = require('args')

args.option('version', 'version opt sub')

const flags = args.parse(process.argv, {version: false})
```

```bash
 $ foo --help

  Usage: foo [options] [command]
  
  Commands:
  
    bar   subcmd
    help  Display help
  
  Options:
  
    -h, --help     Output usage information
    -v, --version  version opt main
  
 $ foo bar --help

  Usage: foo bar [options] [command]
  
  Commands:
  
    help  Display help
  
  Options:
  
    -h, --help     Output usage information
    -v, --version  version opt sub
```

When i remove the `version` option from the main command, the `version` option from the subcommand still works:
`foo.js`
```js
#!/usr/bin/env node

const args = require('args')

args
  .command('bar', 'subcmd')

const flags = args.parse(process.argv)
```
```bash
 $ foo bar --help

  Usage: foo bar [options] [command]
  
  Commands:
  
    help  Display help
  
  Options:
  
    -h, --help     Output usage information
    -v, --version  version opt sub
  
 $ foo --help

  Usage: foo [options] [command]
  
  Commands:
  
    bar   subcmd
    help  Display help
  
  Options:
  
    -h, --help     Output usage information
    -v, --version  Output the version number
```

Can you give us a gist or repo where is does not work?

**Comment by jamesarosen** [comment]
As I said above, it works as I expect if both `foo` and `foo-bar` have `{ version: false }`.

`foo`:
```js
#!/usr/bin/env node
const args = require('args')
args
  .option('version', 'version opt main')
  .command('bar', 'subcmd')
const flags = args.parse(process.argv) // no version: false
console.log(flags)
```

`foo-bar`:
```js
#!/usr/bin/env node
const args = require('args')
args.option('version', 'version opt sub')
const flags = args.parse(process.argv, {version: false})
console.log(flags)
```

```bash
$ PATH=.:$PATH foo bar --version=9
-/-
```

If I add `{ version: false }` to `foo`, then I get
```bash
$ PATH+.:$PATH foo bar --version=9
{}
{ v: '9', version: '9' }
```

That is, in my parent command (`foo`), I don't have use for a `version`. It's only `foo-bar` that knows about it. But unless I set `{ version: false }` on _both_, `foo`'s default one shadows `foo-bar`'s custom one.

**Comment by ntwcklng** [comment]
Oh okay, i've never tested it with the flag, just looked at the `--help` output - my bad! Do you want to commit a fix for that?

**Comment by jamesarosen** [comment]
> Do you want to commit a fix for that?

We actually switched over to [commander](https://www.npmjs.com/package/commander) because it lets us define subcommands' actions in JavaScript rather than require they be on the `PATH`. (That's important because we want to install our commands as dependencies of a project rather than have developers install them with `-g`.)

But my _guess_ is that the relevant code is in [checkVersion](https://github.com/leo/args/blob/15314dc596280234ce551d39e1e37d45eb2a7ff6/lib/utils.js#L321-L344). One oddity there is `if (version)`, but `version` is always truthy because it's defined as

```js
const version = parent.exports.version || '-/-';
```

**Comment by ntwcklng** [comment]
@jamesarosen this is also possible with `args`. You can put your code in the `init` function like this:
```js
args.command('foo','foo subcommand', () => { 
// your code 
})
```
Then, the `init`function gets executed instead of running the binary for the subcommand.

**Comment by jamesarosen** [comment]
I missed

> If a function was passed through at this parameter, args will call it instead of running the binary related to that command. The function receives three arguments:

in the readme. Nice!
