### ISSUE TITLE
minimist to mri is a breaking change in v3.0.5

### ISSUE THREAD

**Issue by icebob** [leo/args#108]
Hi leo,
I think the new v3.0.5 is not just a patch, it is a breaking change. My project is broken after I updated `args` to 3.0.5 from 3.0.4, because you changed `minimist` to `mri` and you removed the `minimist` option from `Args.parse`.

```js
flags = Args.parse(process.argv, {
		minimist: {
			alias: {
				c: "config",
				r: "repl",
				H: "hot",
				s: "silent"
			},
			boolean: ["repl", "silent", "hot"],
			string: ["config"]
		}
	});
servicePaths = Args.sub;
```

It's working with 3.0.4, but not with 3.0.5:
`moleculer-runner --hot --repl examples`.
The `servicePaths` is empty because doesn't process `--repl` as boolean.

I found out that I should rename `minimist` to `mri` in options, but I thought I notify you about it.

**Comment by ntwcklng** [comment]
@icebob my bad! Please update to 3.0.6. Its now backwards compatible.
