### ISSUE TITLE
How to set an option to false when its default value is true

### ISSUE THREAD

**Issue by ibc** [leo/args#110]
Example:

```js
args
  .option([ 't', 'tls' ], 'Use TLS', true);
```

No idea how to set 'tls' to `false` via command line. `script --tls=false` or `script --tls=0` does not work and `flags.tls` remains `true`.

**Comment by ntwcklng** [comment]
Hey @ibc,

in this case you have to tell `mri` or `minimist` that `tls` is a boolean. Please try this:
```js
args
  .option([ 't', 'tls' ], 'Use TLS', true)

const flags = args.parse(process.argv, {
  mri: { 
    boolean: ['tls'] 
  }
})
```
If you're on `args` >=3.0.7 use the  `mri` object to define your booleans. And if you're on `args` <=3.0.6 use `minimist`.

**Comment by ibc** [comment]
Clear. Thanks.
