### ISSUE TITLE
Feature: default command

### ISSUE THREAD

**Issue by chabou** [leo/args#113]
In some situations, developper wants to know if no command has been specified by user.

I see 2 way to achieve this: 
* Let developper define a default command that is executed instead of showing help.
* Let developper retrieve run command the same way as he can retrieve `sub` arg. 

Without this, developper should flag when command is triggered:
```
let commandUsed = false;
args.command(['i', 'install'], 'Install a plugin', (name, args_) => {
  commandUsed = true;
  ...
});

args.command(['u', 'uninstall', 'rm', 'remove'], 'Uninstall a plugin', (name, args_) => {
  commandUsed = true;
  ...
});

args.command(['ls', 'list'], 'List installed plugins', () => {
  commandUsed = true;
  ...
});
```

**Comment by ntwcklng** [comment]
Hey @chabou, if i'm getting this right - this is a duplicate of #84?

**Comment by chabou** [comment]
Command execution obviously stops current program execution... Otherwise my script would not work at all. So, all code after `args.parse()` is the default command

Sorry for the noise... 😊

**Comment by chabou** [comment]
mmh, this is more complicated that what I thought.

From what I see, execution is not stopped if command is matched and executed.
Is it a regression or am I missing something?

```javascript
// cli-test.js
const args = require("args");

args.command(["t", "test"], "Test args lib", () => {
  console.log("Test command is executed");
});

const flags = args.parse(process.argv);

console.log("After parse");
```

```
❯ node cli-test.js test
Test command is executed
After parse
```

**Comment by chabou** [comment]
oh... This is maybe because I don't use sub command binary but I execute code directly in `init` function. Is it an anti-pattern?

**Comment by ntwcklng** [comment]
It _should_ stop after the `init` function.
To define the subcommand `test` (and run the `init` function) you have to add it to the main binary file `cli.js`:

```js
// cli.js
const args = require("args");

args.command(["t", "test"], "Test args lib", () => {
  console.log("Test command is executed");
});

const flags = args.parse(process.argv);

console.log("After parse");
```
I don't have enough time to debug it yet, but both `log` statements gets executed. I've tested the same code a few month ago and it worked back then 🤔
