### ISSUE TITLE
Cannot supply numeric parameters

### ISSUE THREAD

**Issue by micblack** [leo/args#115]
Numbers cannot be passed in to args in this example:

_args.js_

`const args = require('args')`
`args.option('t', 'This is a test', 'foo')`
`const flags = args.parse(process.argv)`
`console.log(flags.t)`

When running:

`$ node args.js`
> returns **foo** correctly

`$ node args.js -t bar`
> returns **bar** correctly

`$ node args.js -t 1000`
> returns **foo** incorrectly

My original use case was to pass in an Ethereum wallet address which is a large hash but also have a default wallet address. The issue was found when I realised no matter what wallet address I sent it, it only ever queried the default address.

Issue occurs on args v3.0.8, node v6.11.3 and node v9.3.0

**Comment by micblack** [comment]
Attempted the same test using 'yargs' library also. Same issue however result returned 'undefined' rather than foo

**Comment by ntwcklng** [comment]
Hey @micblack,
we expect a string, when you add an option with the default parameter of a string. Try to specify the `type` to the `mri` or `minimist` options:

```js
const flags = args.parse(process.argv, {
  mri: {
    string: 't'
  }
})
```

That should solve your issue.
