### ISSUE TITLE
[help] command example

### ISSUE THREAD

**Issue by crobinson42** [leo/args#117]
Hi there, thanks for a great tool!

I'm a bit lost on implementing the command (sub command). 

Here's my code:

// bin/index.js
```
const args = require('args')

args.command('echo', 'Use env vars to set ~/.aws/credentials file', () => console.log('TEST'))
```

// package.json
```
{
...
"bin": {
    "cli-tools": "bin/index.js"
  },
...
}
```

Am I missing something here? Thanks for the help, in advance.

**Comment by ntwcklng** [comment]
Hey @crobinson42 

maybe you've missed to parse the process.argv with args like this: `args.parse(process.argv)` in your `bin/index.js` file.

```js
#!/usr/bin/env node

const args = require('args')

args.command('echo', 'Use env vars to set ~/.aws/credentials file', () =>
  console.log('TEST')
)

args.parse(process.argv)


```

It should work when you run `node bin/index.js echo`

**Comment by crobinson42** [comment]
@ntwcklng ahh you're the man. I was missing the parse invocation. Thx!
