### ISSUE TITLE
Ability to add information to the 'Usage' field

### ISSUE THREAD

**Issue by bcmarinacci** [leo/args#13]
I really like this package and was wondering if you were planning on adding the ability to add information to the 'Usage' field?

For example:
```javascript
Usage: haha [options] [command] <directory>
```

**Comment by leo** [comment]
Thanks for those kind words, really means a lot to me! :blush: I've added a [config option](https://github.com/leo/args#configuration) called "value" which makes this possible. [Here](https://github.com/leo/args/releases/tag/v1.1.0)'s the respective release.

**Comment by bcmarinacci** [comment]
Legend! This is awesome. Thanks heaps.
