### ISSUE TITLE
--help output looks not-so-great with black background terminal

### ISSUE THREAD

**Issue by TooTallNate** [leo/args#19]
<img width="143" alt="screen shot 2016-06-09 at 1 59 18 pm" src="https://cloud.githubusercontent.com/assets/71256/15950540/b4735c42-2e64-11e6-902c-a3697d442c63.png">

The word "Usage" is output in black, making it unreadable. The dark blue isn't the greatest either…

**Comment by leo** [comment]
Should be better now!
