### ISSUE TITLE
Allow `false` default value

### ISSUE THREAD

**Issue by rchipka** [leo/args#25]
Would a pull request be accepted that allows an argument to be false by default? Is there any way of doing this already?

This would be useful for implementing a command line switch to enable a specific function that is disabled by default.

**Comment by rchipka** [comment]
I suppose a workaround would be to simply not define a default type and assume that `undefined` means false.

This solution works fine, however I don't see any harm in allowing an arg to have a default type `false`.

**Comment by leo** [comment]
Generally: Yes, we could implement that. So far I've been using the method of simply not defining the default value. But like you said, it wouldn't hurt to specify a default value of "false". I mean, it's not really necessary, but I also don't see a reason why we shouldn't implement it.

However, I'd like to clarify that there's no "default type" (like you said it), there's only a "default value" (the third parameter on the `.option` method.

**Comment by leo** [comment]
@rchipka Interested in doing a PR?

**Comment by rchipka** [comment]
@leo I'll try to create a PR sometime today. However, you can probably close this issue since it's more of a feature request.
