### ISSUE TITLE
allow to pass minimist options to parser

### ISSUE THREAD

**Issue by dlebedynskyi** [leo/args#45]
since this one does not allow to pass 2nd argument `opts` to minimist 
https://github.com/leo/args/blob/master/src/index.js#L387

there is no way to make parser treat number looking values as strings like here https://github.com/substack/minimist#var-argv--parseargsargs-opts.

**Comment by codyzu** [comment]
@leo do you prefer a 3rd parameter to `parse()` or adding a property like `minimistOptions` to the config object (2nd parameter). I think I prefer the later, any opinion on your side?

**Comment by leo** [comment]
@codyzu I also prefer the latter! Please call just call it `minimist`. 😊
