### ISSUE TITLE
List authors of CLI when running `author|authors` sub command

### ISSUE THREAD

**Issue by leo** [leo/args#59]
This will make it easy for devs to find out who created a CLI

**Comment by mfix22** [comment]
Were you thinking as simple as something like this?

_Single Author_
![Author](http://i.imgur.com/vbBxZ3U.png)

_List of Authors_
![Authors](http://i.imgur.com/COJYUcJ.png)

_or even_
![Collaborators](http://i.imgur.com/mL3hJG7.png)

**Comment by leo** [comment]
The second one looks good! It's important that we're reading this from `package.json`, so that we're not adding another available property.
