### ISSUE TITLE
Config as an API-Method

### ISSUE THREAD

**Issue by ntwcklng** [leo/args#66]
I think this syntax is more readable and easier to understand:

```javascript
args
  .option('a', 'abc')
  .command('b', 'def')
  .config({name: 'abcdef'})

args.parse(process.argv)
```
What do you think?

**Comment by leo** [comment]
Yep, that would definitely be more readable.

But not easier and more confusing in my opinion. Mainly because it's not related at all to the stuff that shows up in the usage information (options and commands).

🙏
