### ISSUE TITLE
ENOENT error for spawning child processes

### ISSUE THREAD

**Issue by mfix22** [leo/args#69]
Hey @leo,
This fix might not be necessary, but when I created my first args subcommand I got:

```
Error: spawn gest-test ENOENT
    at exports._errnoException (util.js:1028:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    ...
```

and adding`path.join(__dirname, this.binary + '-' + (Array.isArray(details.usage) ? details.usage[0] : details.usage))` was my quick fix, but this only fixed the problem if I named my binary `gest-test`, not `gest-test.js`. A better solution would be to only spawn the file mapped to by `package.json`'s `bin`, or maybe default to `.js`.

I can tackle this, but I would like to know which approach you think is best.
-- @mfix22

**Comment by mfix22** [comment]
Here is an example of what I was thinking:
```
// Generate full name of binary
const bin = module.parent.exports.bin
const full = this.binary + '-' + (Array.isArray(details.usage) ? details.usage[0] : details.usage)
const binFull = path.join(__dirname, bin[full] || `${full}.js`)
...
this.child = spawn(binFull, args, {
```

**Comment by ntwcklng** [comment]
I also experimented with this a while ago - my working example was:
```js
const bin = process.mainModule.filename
const subCommand = (Array.isArray(details.usage) ? details.usage[0] : details.usage)
const fullPath = path.join(bin.split(path.sep).slice(0, -1).join(path.sep) + '/' + this.binary + '-' + subCommand)
const ext = path.extname(bin)
let binFull = fullPath

if (ext.length > 0) {
  const withExt = path.basename(bin, ext) + '-' + subCommand + ext
  binFull = path.join(bin.split(path.sep).slice(0, -1).join(path.sep) + '/' + withExt)
}

this.child = spawn(binFull, args, {
...
```
The problem with that is that you have to `chmod +x` all binaries while developing. Otherwise you get `Error: spawn EACCES`.
I think adding the binaries to the `package.json` and run `npm link` is the easiest and best solution. See #46

**Comment by mfix22** [comment]
@ntwcklng I have not had a problem with that since I test my 'binaries' as `node ./bin/gest-test.js [options]`, so I don't run into the `EACCES` error. I think the solution I posted tackles two issues: 1. it defaults to looking in `package.json` for the paths to your binaries and 2. defaults to use a `.js` extension if you don't put them in `package.json`.

The only two issues I was running into was that the it wasn't finding the file without `__dirname` and secondly it was looking for a binary without the `.js` extension (which I would like to keep for syntax highlighting etc.)

**Comment by ntwcklng** [comment]
Okay, defaults to use the `.js` extension would break a lot of projects. 
Whats wrong with `npm link` and adding the binaries to `package.json`? Then you can also test your bins with `node ./bin/gest-test.js`

**Comment by mfix22** [comment]
Actually, I am with you there. Thanks for challenging my point, I agree!

**Comment by ntwcklng** [comment]
We should document this process better

**Comment by mfix22** [comment]
@ntwcklng yeah it was really just a matter of my understanding how `args` worked. If anything, documenting better should be a different issue. Closing.
