### ISSUE TITLE
Automatically show help only for options, not sub commands

### ISSUE THREAD

**Issue by leo** [leo/args#79]
@ntwcklng We kinda forgot that people need to be able to specify an unknown sub command, as a path to a directory or similar:

```
serve directory
```

```
micro directory
```

Both of these would throw the help, because the "sub command" is unknown.

Of course we could just add the ability to deactivate this using a config parameter, but since these are like 90% of the cases, I would rather only use it for options, not sub commands. 😊 🙏

**Comment by leo** [comment]
Until we've fixed this, I made 2.4.2 latest on npm

**Comment by ntwcklng** [comment]
Thats even my use case with `next-new` 😅
What about this: only show help when there is a similar subcommand registered? We could bump the rating a bit up to be sure.
Adding the suggestions also to `options` is a good idea.

**Comment by leo** [comment]
I think that's not such a good idea, because there will be cases in which the directory or file passed as a value will have the same name as a sub command. Can we simply use it for flags? 😊
