### ISSUE TITLE
Move away from exporting a class and split methods into separate files

### ISSUE THREAD

**Issue by leo** [leo/args#81]
This will make managing the code and adding features in the future much easier!

**Comment by ntwcklng** [comment]
@leo do you mean something like this: https://github.com/ntwcklng/args/tree/refactor-class

**Comment by leo** [comment]
Yep! But the files should export the functions as default export (`module.exports = `).

**Comment by ntwcklng** [comment]
Okay, so methods like `.option` and `.options` should get their own file, but not the the 8 `.util` methods i guess?
If you're generally happy with my structure, i will continue to work on this.

**Comment by leo** [comment]
Right! 😊 That would be great.

**Comment by ntwcklng** [comment]
Done via #82
