### ISSUE TITLE
cannot name an option "version"

### ISSUE THREAD

**Issue by jasonsirota** [leo/args#98]
I want to specify a string option named "--version" but because of the default version option, it will not let me override it (as far as I can tell). I can submit a patch if this isn't supported.

**Comment by ntwcklng** [comment]
Hey jasonsirota,

you can set the `version` in the config to `false` and create an option named `version`. e.g.

```js
const args = require('args')

args.option('version', 'description')

const flags = args.parse(process.argv, {version: false})
```
